<?php $this->headTitle('Change password') ?>
<div class="container">
    <h2>Change password</h2>
    <div class="row">
    <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?> 
    <?php if ($flashMessenger->setNamespace('error')->hasMessages()): ?>
        <div class="alert alert-danger col-sm-4">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($flashMessenger->setNamespace('success')->hasMessages()): ?>
        <div class="alert alert-success col-sm-4">
        <?php foreach ($flashMessenger->getMessages() as $msg): ?>
            <?php echo $msg ?>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
    </div>
    <?php echo $this->form; ?>
</div>